---
- name: Install Homebrew on macOS
  hosts: macos
  gather_facts: yes
  become: yes
  tasks:
    - name: Install Homebrew
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      args:
        creates: /usr/local/bin/brew
