---
- name: Download Chrome.pkg to Downloads folder
  hosts: macos
  gather_facts: yes
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Download Chrome.pkg
      command: >
        curl -L -o ~/Downloads/Chrome.pkg https://dl.google.com/chrome/mac/universal/stable/CHFA/googlechrome.dmg
      args:
        creates: ~/Downloads/Chrome.pkg
      when: ansible_os_family == "Darwin"
