---
- name: Download Chrome.pkg to Downloads folder
  hosts: macos
  gather_facts: yes
  become: yes
    tasks:
    - name: Download Chrome.pkg
      command: >
        curl -L -o /Users/admin/Downloads/Chrome.pkg https://dl.google.com/chrome/mac/universal/stable/CHFA/googlechrome.dmg
      args:
        creates: /Users/admin/Downloads/Chrome.pkg
