---
- name: Download Chrome.pkg to Downloads folder
  hosts: macos
  gather_facts: yes
  become: yes
  tasks:
    - name: Create Downloads folder if it doesn't exist
      file:
        path: ~/Documents
        state: directory
      when: ansible_os_family == "Darwin"

    - name: Download Chrome.pkg
      command: >
        curl -L -o ~/Documents/Chrome.pkg https://dl.google.com/chrome/mac/universal/stable/CHFA/googlechrome.dmg
      args:
        creates: ~/Documents/Chrome.pkg
      when: ansible_os_family == "Darwin"
